name: n8n_to_go
description: "n8n to go is a mobile application that allows you to access and manage your n8n workflows on the go. With n8n to go, you can easily monitor and control your n8n instances from your smartphone, ensuring that your automation processes are always within reach."
publish_to: "none"
version: 0.1.0+1

environment:
   sdk: ^3.11.0

dependencies:
   flutter:
      sdk: flutter
   flutter_dotenv: ^6.0.0
   flutter_secure_storage: ^9.2.4
   shared_preferences: ^2.3.0
   google_fonts: ^8.0.2
   http: ^1.2.0
   shadcn_ui: ^0.52.1
   shadcn_flutter: ^0.0.52

dev_dependencies:
   flutter_test:
      sdk: flutter
   flutter_lints: ^6.0.0
   flutter_launcher_icons: ^0.14.3
   flutter_native_splash: ^2.4.3

flutter_native_splash:
   color: "#ffffff"
   image: lib/assets/app-logo.png
   android: true
   ios: false
   android_12:
      color: "#ffffff"
      image: lib/assets/app-logo.png

flutter_launcher_icons:
   android: true
   ios: false
   image_path: "lib/assets/app-logo.png"

flutter:
   uses-material-design: true
   assets:
      - .env
      - lib/assets/app-logo.png
      - lib/assets/appbar-logo.svg
      - lib/assets/credentials/
      - lib/assets/splash-screem.svg
