// ignore_for_file: file_names

const Map<String, String> credentialTypes = {
  // A
  //   'Action Network API': 'actionNetworkApi',
  //   'ActiveCampaign API': 'activeCampaignApi',
  //   'Acuity Scheduling API': 'acuitySchedulingApi',
  //   'AcuityScheduling OAuth2 API': 'acuitySchedulingOAuth2Api',
  //   'Adalo API': 'adaloApi',
  //   'Affinity API': 'affinityApi',
  //   'AgileCRM API': 'agileCrmApi',
  //   'Airtable API': 'airtableApi',
  //   'Airtable OAuth2 API': 'airtableOAuth2Api',
  //   'Airtable Personal Access Token API': 'airtablePersonalAccessTokenApi',
  //   'Airtop API': 'airtopApi',
  //   'AlienVault API': 'alienVaultApi',
  //   'AMQP': 'amqp',
  //   'Anthropic': 'anthropicApi',
  //   'APITemplate.io API': 'apiTemplateIoApi',
  //   'Asana API': 'asanaApi',
  //   'Asana OAuth2 API': 'asanaOAuth2Api',
  //   'Auth0 Management API': 'auth0ManagementApi',
  //   'Automizy API': 'automizyApi',
  //   'Autopilot API': 'autopilotApi',
  //   'AWS (Assume Role)': 'awsAssumeRole',
  //   'AWS (IAM)': 'aws',
  //   'Azure AI Search API': 'azureAiSearchApi',
  //   'Azure Entra ID (Azure Active Directory) API': 'microsoftEntraIdApi',
  //   'Azure Open AI': 'azureOpenAiApi',
  //   'Azure Storage OAuth2 API': 'azureStorageOAuth2Api',
  //   'Azure Storage Shared Key API': 'azureStorageSharedKeyApi',
  //   // B
  //   'BambooHR API': 'bambooHrApi',
  //   'Bannerbear API': 'bannerbearApi',
  //   'Baserow API': 'baserowApi',
  //   'Basic Auth': 'httpBasicAuth',
  'Bearer Auth': 'httpHeaderAuth',
  //   'Beeminder API': 'beminderApi',
  //   'Beeminder OAuth2 API': 'beminderOAuth2Api',
  //   'Bitbucket Access Token API': 'bitbucketAccessTokenApi',
  //   'Bitbucket API': 'bitbucketApi',
  //   'Bitly API': 'bitlyApi',
  //   'Bitly OAuth2 API': 'bitlyOAuth2Api',
  //   'Bitwarden API': 'bitwardenApi',
  //   'Box OAuth2 API': 'boxOAuth2Api',
  //   'Brandfetch API': 'brandfetchApi',
  //   'Brevo': 'brevoApi',
  //   'Bubble API': 'bubbleApi',
  //   // C
  //   'Cal API': 'calApi',
  //   'Calendly API': 'calendlyApi',
  //   'Calendly OAuth2 API': 'calendlyOAuth2Api',
  //   'Carbon Black API': 'carbonBlackApi',
  //   'Chargebee API': 'chargebeeApi',
  //   'Chat OAuth2 API': 'chatOAuth2Api',
  //   'CircleCI API': 'circleCiApi',
  //   'Cisco Meraki API': 'ciscoMerakiApi',
  //   'Cisco Secure Endpoint (AMP) API': 'ciscoSecureEndpointApi',
  //   'Cisco Umbrella API': 'ciscoUmbrellaApi',
  //   'Cisco Webex OAuth2 API': 'ciscoWebexOAuth2Api',
  //   'Clearbit API': 'clearbitApi',
  //   'ClickUp API': 'clickUpApi',
  //   'ClickUp OAuth2 API': 'clickUpOAuth2Api',
  //   'Clockify API': 'clockifyApi',
  //   'Cloudflare API': 'cloudflareApi',
  //   'Cockpit API': 'cockpitApi',
  //   'Coda API': 'codaApi',
  //   'CohereApi': 'cohereApi',
  //   'Contentful API': 'contentfulApi',
  //   'ConvertAPI': 'convertApi',
  //   'ConvertKit API': 'convertKitApi',
  //   'Copper API': 'copperApi',
  //   'Cortex API': 'cortexApi',
  //   'CrateDB': 'crateDb',
  //   'crowd.dev API': 'crowdDevApi',
  //   'CrowdStrike OAuth2 API': 'crowdStrikeOAuth2Api',
  //   'Custom Auth': 'httpCustomAuth',
  //   'Customer.io API': 'customerIoApi',
  //   // D
  //   'Datadog API': 'datadogApi',
  //   'DeepL API': 'deeplApi',
  //   'DeepSeek': 'deepSeekApi',
  //   'Demio API': 'demioApi',
  //   'DFIR-IRIS API': 'dfirIrisApi',
  //   'DHL API': 'dhlApi',
  //   'Digest Auth': 'httpDigestAuth',
  //   'Discord Bot API': 'discordBotApi',
  //   'Discord OAuth2 API': 'discordOAuth2Api',
  //   'Discord Webhook': 'discordWebhook',
  //   'Discourse API': 'discourseApi',
  //   'Disqus API': 'disqusApi',
  //   'Drift API': 'driftApi',
  //   'Drift OAuth2 API': 'driftOAuth2Api',
  //   'Dropbox API': 'dropboxApi',
  //   'Dropbox OAuth2 API': 'dropboxOAuth2Api',
  //   'Dropcontact API': 'dropcontactApi',
  'DynatraceAPI': 'dynatraceApi',
  //   // E
  //   'E-Goi API': 'eGoiApi',
  'Elastic Security API': 'elasticSecurityApi',
  //   'Elasticsearch API': 'elasticsearchApi',
  //   'Emelia API': 'emeliaApi',
  //   'ERPNext API': 'erpNextApi',
  //   'Eventbrite API': 'eventbriteApi',
  //   'Eventbrite OAuth2 API': 'eventbriteOAuth2Api',
  //   // F
  //   'F5 Big-IP API': 'f5BigIpApi',
  //   'Facebook Graph API': 'facebookGraphApi',
  //   'Facebook Graph API (App)': 'facebookGraphApiApp',
  //   'Facebook Lead Ads OAuth2 API': 'facebookLeadAdsOAuth2Api',
  //   'Figma API': 'figmaApi',
  //   'FileMaker API': 'fileMakerApi',
  'Filescan API': 'filescanApi',
  //   'Flow API': 'flowApi',
  //   'Form.io API': 'formIoApi',
  //   'Formstack API': 'formstackApi',
  //   'Formstack OAuth2 API': 'formstackOAuth2Api',
  'Fortinet FortiGate API': 'fortinetFortiGateApi',
  //   'Freshdesk API': 'freshdeskApi',
  //   'Freshservice API': 'freshserviceApi',
  //   'Freshworks CRM API': 'freshworksCrmApi',
  //   'FTP': 'ftp',
  //   // G
  //   'GetResponse API': 'getResponseApi',
  //   'GetResponse OAuth2 API': 'getResponseOAuth2Api',
  //   'Ghost Admin API': 'ghostAdminApi',
  //   'Ghost Content API': 'ghostContentApi',
  //   'Git': 'gitCredentials',
  //   'GitHub API': 'githubApi',
  //   'GitHub OAuth2 API': 'githubOAuth2Api',
  //   'GitLab API': 'gitlabApi',
  //   'GitLab OAuth2 API': 'gitlabOAuth2Api',
  //   'Gmail OAuth2 API': 'gmailOAuth2',
  //   'Gong API': 'gongApi',
  //   'Gong OAuth2 API': 'gongOAuth2Api',
  //   'Google Ads OAuth2 API': 'googleAdsOAuth2Api',
  //   'Google Analytics OAuth2 API': 'googleAnalyticsOAuth2Api',
  //   'Google BigQuery OAuth2 API': 'googleBigQueryOAuth2Api',
  //   'Google Books OAuth2 API': 'googleBooksOAuth2Api',
  //   'Google Business Profile OAuth2 API': 'googleBusinessProfileOAuth2Api',
  //   'Google Calendar OAuth2 API': 'googleCalendarOAuth2Api',
  //   'Google Cloud Natural Language OAuth2 API': 'googleCloudNaturalLanguageOAuth2Api',
  //   'Google Cloud Storage OAuth2 API': 'googleCloudStorageOAuth2Api',
  //   'Google Contacts OAuth2 API': 'googleContactsOAuth2Api',
  //   'Google Docs OAuth2 API': 'googleDocsOAuth2Api',
  //   'Google Drive OAuth2 API': 'googleDriveOAuth2Api',
  //   'Google Firebase Cloud Firestore OAuth2 API': 'googleFirebaseCloudFirestoreOAuth2Api',
  //   'Google Firebase Realtime Database OAuth2 API': 'googleFirebaseRealtimeDatabaseOAuth2Api',
  //   'Google Gemini(PaLM) Api': 'googlePalmApi',
  //   'Google OAuth2 API': 'googleOAuth2Api',
  'Google Palm API': 'googlePalmApi',
  //   'Google Perspective OAuth2 API': 'googlePerspectiveOAuth2Api',
  //   'Google Service Account API': 'googleServiceAccountApi',
  //   'Google Sheets OAuth2 API': 'googleSheetsOAuth2Api',
  //   'Google Sheets Trigger OAuth2 API': 'googleSheetsTriggerOAuth2Api',
  //   'Google Slides OAuth2 API': 'googleSlidesOAuth2Api',
  //   'Google Tasks OAuth2 API': 'googleTasksOAuth2Api',
  //   'Google Translate OAuth2 API': 'googleTranslateOAuth2Api',
  //   'Google Workspace Admin OAuth2 API': 'googleWorkspaceAdminOAuth2Api',
  //   'Gotify API': 'gotifyApi',
  //   'GoToWebinar OAuth2 API': 'goToWebinarOAuth2Api',
  //   'Grafana API': 'grafanaApi',
  //   'Grist API': 'gristApi',
  //   'Groq': 'groqApi',
  //   'Gumroad API': 'gumroadApi',
  //   // H
  //   'HaloPSA API': 'haloPsaApi',
  //   'Harvest API': 'harvestApi',
  //   'Harvest OAuth2 API': 'harvestOAuth2Api',
  //   'Header Auth': 'httpHeaderAuth',
  //   'HelpScout OAuth2 API': 'helpScoutOAuth2Api',
  //   'HighLevel API': 'highLevelApi',
  //   'HighLevel OAuth2 API': 'highLevelOAuth2Api',
  //   'Home Assistant API': 'homeAssistantApi',
  //   'HTTP Basic Auth': 'httpBasicAuth',
  //   'HubSpot API': 'hubspotApi',
  //   'HubSpot App Token': 'hubspotAppToken',
  //   'HubSpot Developer API': 'hubspotDeveloperApi',
  //   'HubSpot OAuth2 API': 'hubspotOAuth2Api',
  //   'HuggingFaceApi': 'huggingFaceApi',
  //   'Humantic AI API': 'humanticAiApi',
  //   'Hunter API': 'hunterApi',
  //   'Hybrid Analysis API': 'hybridAnalysisApi',
  //   // I
  //   'IMAP': 'imap',
  //   'Imperva WAF API': 'impervaWafApi',
  //   'Intercom API': 'intercomApi',
  //   'Invoice Ninja API': 'invoiceNinjaApi',
  //   'Iterable API': 'iterableApi',
  //   // J
  //   'Jenkins API': 'jenkinsApi',
  //   'Jina AI API': 'jinaAiApi',
  //   'Jira SW Cloud API': 'jiraSoftwareCloud',
  //   'Jira SW Server (PAT) API': 'jiraSoftwareServerPat',
  //   'Jira SW Server API': 'jiraSoftwareServer',
  //   'JotForm API': 'jotFormApi',
  //   'JWT Auth': 'jwtAuth',
  //   // K
  //   'Kafka': 'kafka',
  //   'Keap OAuth2 API': 'keapOAuth2Api',
  //   'Kibana API': 'kibanaApi',
  //   'Kitemaker API': 'kitemakerkApi',
  //   'KoBoToolbox API Token': 'koBoToolboxApi',
  //   // L
  //   'LDAP': 'ldap',
  //   'Lemlist API': 'lemlistApi',
  //   'Lemonade': 'lemonadeApi',
  //   'Line Notify OAuth2 API': 'lineNotifyOAuth2Api',
  //   'Linear API': 'linearApi',
  //   'Linear OAuth2 API': 'linearOAuth2Api',
  //   'LingvaNex API': 'lingvaNexApi',
  //   'LinkedIn Community Management OAuth2 API': 'linkedInCommunityManagementOAuth2Api',
  //   'LinkedIn OAuth2 API': 'linkedInOAuth2Api',
  //   'LoneScale API': 'loneScaleApi',
  //   // M
  //   'Magento 2 API': 'magento2Api',
  //   'Mailcheck API': 'mailcheckApi',
  //   'Mailchimp API': 'mailchimpApi',
  //   'Mailchimp OAuth2 API': 'mailchimpOAuth2Api',
  //   'Mailer Lite API': 'mailerLiteApi',
  //   'Mailgun API': 'mailgunApi',
  //   'Mailjet Email API': 'mailjetEmailApi',
  //   'Mailjet SMS API': 'mailjetSmsApi',
  //   'MalcoreAPI': 'malcoreApi',
  //   'Mandrill API': 'mandrillApi',
  //   'Marketstack API': 'marketstackApi',
  //   'Matrix API': 'matrixApi',
  //   'Mattermost API': 'mattermostApi',
  //   'Mautic API': 'mauticApi',
  //   'Mautic OAuth2 API': 'mauticOAuth2Api',
  //   'MCP OAuth2 API': 'mcpOAuth2Api',
  //   'Medium API': 'mediumApi',
  //   'Medium OAuth2 API': 'mediumOAuth2Api',
  //   'MessageBird API': 'messageBirdApi',
  //   'Metabase API': 'metabaseApi',
  //   'Microsoft Azure Cosmos DB API': 'microsoftAzureCosmosDbApi',
  //   'Microsoft Azure Monitor OAuth2 API': 'microsoftAzureMonitorOAuth2Api',
  //   'Microsoft Drive OAuth2 API': 'microsoftDriveOAuth2Api',
  //   'Microsoft Dynamics OAuth2 API': 'microsoftDynamicsOAuth2Api',
  //   'Microsoft Entra ID (Azure Active Directory) API': 'microsoftEntraIdApi',
  //   'Microsoft Excel OAuth2 API': 'microsoftExcelOAuth2Api',
  //   'Microsoft Graph Security OAuth2 API': 'microsoftGraphSecurityOAuth2Api',
  //   'Microsoft OAuth2 API': 'microsoftOAuth2Api',
  //   'Microsoft Outlook OAuth2 API': 'microsoftOutlookOAuth2Api',
  //   'Microsoft SharePoint OAuth2 API': 'microsoftSharePointOAuth2Api',
  //   'Microsoft SQL': 'microsoftSql',
  //   'Microsoft Teams OAuth2 API': 'microsoftTeamsOAuth2Api',
  //   'Microsoft To Do OAuth2 API': 'microsoftToDoOAuth2Api',
  //   'Milvus': 'milvusApi',
  //   'Mindee Invoice API': 'mindeeInvoiceApi',
  //   'Mindee Receipt API': 'mindeeReceiptApi',
  'Miro OAuth2 API': 'miroOAuth2Api',
  //   'MISP API': 'mispApi',
  'Mist API': 'mistApi',
  //   'Mistral Cloud API': 'mistralCloudApi',
  //   'Mocean Api': 'moceanApi',
  //   'Monday.com API': 'mondayComApi',
  //   'Monday.com OAuth2 API': 'mondayComOAuth2Api',
  'MongoDB': 'mongoDb',
  //   'Monica CRM API': 'monicaCrmApi',
  //   'MotorheadApi': 'motorheadApi',
  //   'MQTT': 'mqtt',
  //   'Msg91 Api': 'msg91Api',
  //   'Multiple Headers Auth': 'httpMultipleHeadersAuth',
  //   'MySQL': 'mySql',
  //   // N
  //   'n8n API': 'n8nApi',
  //   'NASA API': 'nasaApi',
  //   'Netlify API': 'netlifyApi',
  //   'Netscaler ADC API': 'netscalerAdcApi',
  //   'NextCloud API': 'nextCloudApi',
  //   'NextCloud OAuth2 API': 'nextCloudOAuth2Api',
  //   'NocoDB': 'nocoDb',
  //   'NocoDB API Token': 'nocoDbApiToken',
  //   'Notion API': 'notionApi',
  //   'Notion OAuth2 API': 'notionOAuth2Api',
  //   'Npm API': 'npmApi',
  //   // O
  //   'OAuth1 API': 'oAuth1Api',
  //   'OAuth2 API': 'oAuth2Api',
  //   'Odoo API': 'odooApi',
  'Okta API': 'oktaApi',
  'Ollama': 'ollamaApi',
  //   'Ollama API': 'ollamaApi',
  //   'One Simple API': 'oneSimpleApi',
  //   'Onfleet API': 'onfleetApi',
  //   'OpenAi': 'openAiApi',
  //   'OpenAI API': 'openAiApi',
  //   'OpenCTI API': 'openCtiApi',
  //   'OpenRouter': 'openRouterApi',
  //   'OpenWeatherMap API': 'openWeatherMapApi',
  //   'Oracle Database Credentials API': 'oracleDb',
  //   'Orbit API': 'orbitApi',
  //   'Oura API': 'ouraApi',
  //   // P
  //   'Paddle API': 'paddleApi',
  //   'PagerDuty API': 'pagerDutyApi',
  //   'PagerDuty OAuth2 API': 'pagerDutyOAuth2Api',
  //   'PayPal API': 'payPalApi',
  //   'Peekalink API': 'peekalinkApi',
  //   'Perplexity API': 'perplexityApi',
  //   'Phantombuster API': 'phantombusterApi',
  //   'PhilipHue OAuth2 API': 'philipsHueOAuth2Api',
  //   'PineconeApi': 'pineconeApi',
  //   'Pipedrive API': 'pipedriveApi',
  //   'Pipedrive OAuth2 API': 'pipedriveOAuth2Api',
  //   'Plivo API': 'plivoApi',
  'Postgres': 'postgres',
  //   'PostHog API': 'postHogApi',
  //   'Postmark API': 'postmarkApi',
  //   'ProfitWell API': 'profitWellApi',
  //   'Pushbullet OAuth2 API': 'pushbulletOAuth2Api',
  //   'Pushcut API': 'pushcutApi',
  //   'Pushover API': 'pushoverApi',
  //   // Q
  //   'QdrantApi': 'qdrantApi',
  //   'QRadar API': 'qRadarApi',
  'Qualys API': 'qualysApi',
  //   'Query Auth': 'httpQueryAuth',
  //   'QuestDB': 'questDb',
  //   'Quick Base API': 'quickBaseApi',
  //   'QuickBooks Online OAuth2 API': 'quickBooksOAuth2Api',
  //   // R
  'RabbitMQ': 'rabbitmq',
  //   'Raindrop OAuth2 API': 'raindropOAuth2Api',
  //   'Rapid7 InsightVM API': 'rapid7InsightVmApi',
  'Recorded Future API': 'recordedFutureApi',
  //   'Reddit OAuth2 API': 'redditOAuth2Api',
  'Redis': 'redis',
  //   'Rocket API': 'rocketApi',
  //   'Rundeck API': 'rundeckApi',
  //   // S
  //   'S3': 'aws',
  //   'Salesforce JWT API': 'salesforceJwtApi',
  //   'Salesforce OAuth2 API': 'salesforceOAuth2Api',
  //   'Salesmate API': 'salesmateApi',
  //   'SearXNG': 'searXngApi',
  //   'SeaTable API': 'seaTableApi',
  //   'SecurityScorecard API': 'securityScorecardApi',
  //   'Segment API': 'segmentApi',
  'Sekoia API': 'sekoiaApi',
  //   'SendGrid API': 'sendGridApi',
  //   'Sendy API': 'sendyApi',
  //   'Sentry.io API': 'sentryIoApi',
  //   'Sentry.io OAuth2 API': 'sentryIoOAuth2Api',
  //   'Sentry.io Server API': 'sentryIoServerApi',
  //   'SerpAPI': 'serpApi',
  //   'ServiceNow Basic Auth API': 'serviceNowBasicAuthApi',
  //   'ServiceNow OAuth2 API': 'serviceNowOAuth2Api',
  //   'seven API': 'sevenApi',
  //   'SFTP': 'sftp',
  //   'Shopify Access Token API': 'shopifyAccessTokenApi',
  //   'Shopify API': 'shopifyApi',
  //   'Shopify OAuth2 API': 'shopifyOAuth2Api',
  'Shuffler API': 'shufflerApi',
  //   'SIGNL4 Webhook': 'signl4Webhook',
  //   'Slack API': 'slackApi',
  //   'Slack OAuth2 API': 'slackOAuth2Api',
  //   'SMTP': 'smtp',
  //   'Snowflake': 'snowflake',
  'SolarWinds IPAM': 'solarWindsIpamApi',
  'SolarWinds Observability': 'solarWindsObservabilityApi',
  //   'Splunk API': 'splunkApi',
  //   'Spontit API': 'spontitApi',
  //   'Spotify OAuth2 API': 'spotifyOAuth2Api',
  //   'SSH Password': 'sshPassword',
  //   'SSH Private Key': 'sshPrivateKey',
  //   'SSL Certificates': 'sslCertificates',
  //   'Stackby API': 'stackbyApi',
  //   'Storyblok Content API': 'storyblokContentApi',
  //   'Storyblok Management API': 'storyblokManagementApi',
  //   'Strapi API': 'strapiApi',
  //   'Strapi API Token': 'strapiApiToken',
  //   'Strava OAuth2 API': 'stravaOAuth2Api',
  //   'Stripe API': 'stripeApi',
  //   'Supabase API': 'supabaseApi',
  //   'SurveyMonkey API': 'surveyMonkeyApi',
  //   'SurveyMonkey OAuth2 API': 'surveyMonkeyOAuth2Api',
  //   'SyncroMSP API': 'syncroMspApi',
  'Sysdig API': 'sysdigApi',
  //   // T
  //   'Taiga API': 'taigaApi',
  //   'Tapfiliate API': 'tapfiliateApi',
  'Telegram API': 'telegramApi',
  //   'The Hive 5 API': 'theHive5Api',
  //   'The Hive API': 'theHiveApi',
  //   'TimescaleDB': 'timescaleDb',
  //   'Todoist API': 'todoistApi',
  //   'Todoist OAuth2 API': 'todoistOAuth2Api',
  //   'Toggl API': 'togglApi',
  //   'TOTP API': 'totpApi',
  //   'Travis API': 'travisApi',
  'Trellix (McAfee) ePolicy Orchestrator API': 'trellixEpoApi',
  //   'Trello API': 'trelloApi',
  //   'Twake Cloud API': 'twakeCloudApi',
  //   'Twake Server API': 'twakeServerApi',
  //   'Twilio API': 'twilioApi',
  //   'Twist OAuth2 API': 'twistOAuth2Api',
  //   'Typeform API': 'typeformApi',
  //   'Typeform OAuth2 API': 'typeformOAuth2Api',
  //   // U
  //   'Unleashed API': 'unleashedApi',
  //   'Uplead API': 'upleadApi',
  //   'uProc API': 'uProcApi',
  //   'Uptime Robot API': 'uptimeRobotApi',
  //   'urlscan.io API': 'urlscanIoApi',
  //   // V
  //   'Venafi TLS Protect Cloud': 'venafiTlsProtectCloudApi',
  //   'Venafi TLS Protect Datacenter API': 'venafiTlsProtectDatacenterApi',
  //   'Vercel AI Gateway': 'vercelAiGatewayApi',
  //   'Vero API': 'veroApi',
  //   'Vertica API': 'verticaApi',
  'VirusTotal API': 'virusTotalApi',
  //   'Vonage API': 'vonageApi',
  //   // W
  //   'Weaviate Credentials': 'weaviateApi',
  //   'Webflow API': 'webflowApi',
  //   'Webflow OAuth2 API': 'webflowOAuth2Api',
  //   'Wekan API': 'wekanApi',
  //   'WhatsApp API': 'whatsAppApi',
  //   'WhatsApp OAuth API': 'whatsAppOAuthApi',
  //   'Wise API': 'wiseApi',
  //   'WolframAlphaApi': 'wolframAlphaApi',
  //   'WooCommerce API': 'wooCommerceApi',
  //   'Wordpress API': 'wordpressApi',
  //   'Workable API': 'workableApi',
  //   'Wufoo API': 'wufooApi',
  //   // X
  //   'X OAuth API': 'twitterOAuth1Api',
  //   'X OAuth2 API': 'twitterOAuth2Api',
  //   'xAi': 'xAiApi',
  //   'Xata Api': 'xataApi',
  //   'Xero OAuth2 API': 'xeroOAuth2Api',
  //   // Y
  //   'Yourls API': 'yourlsApi',
  //   'YouTube OAuth2 API': 'youTubeOAuth2Api',
  //   // Z
  'Zabbix API': 'zabbixApi',
  //   'Zammad Basic Auth API': 'zammadBasicAuthApi',
  //   'Zammad Token Auth API': 'zammadTokenAuthApi',
  //   'Zendesk API': 'zendeskApi',
  //   'Zendesk OAuth2 API': 'zendeskOAuth2Api',
  //   'Zep Api': 'zepApi',
  //   'Zoho OAuth2 API': 'zohoOAuth2Api',
  //   'Zoom API': 'zoomApi',
  //   'Zoom OAuth2 API': 'zoomOAuth2Api',
  'Zscaler ZIA API': 'zscalerZiaApi',
  //   'Zulip API': 'zulipApi',
};
